### ISSUE TITLE
allow containers 0.6 / ghc 8.6

### ISSUE THREAD

**Issue by simonmichael** [liamoc/wizards#11]
Could the containers upper bound be bumped to allow 0.6.x which comes with GHC 8.6.1. I have built hledger with it and seen no problems.

**Comment by simonmichael** [comment]
Thanks, is a release planned ?

**Comment by simonmichael** [comment]
Ping, @liamoc could you make a release or revision to allow containers 0.6 ?

**Comment by liamoc** [comment]
Done. Sorry for the delay.

**Comment by simonmichael** [comment]
Thanks!
