### ISSUE TITLE
needs a release/revision for haskeline 0.8

### ISSUE THREAD

**Issue by simonmichael** [liamoc/wizards#13]
Hi @liamoc ! Might you be able to make a hackage revision (if sufficient) or a new release (otherwise) so that wizards can build with latest haskeline ([changelog](http://hackage.haskell.org/package/haskeline-0.8.0.0/changelog)) ? This is needed to allow haskeline, wizards and hledger to coexist in stackage, cf https://github.com/commercialhaskell/stackage/issues/5269.

**Comment by liamoc** [comment]
I am not maintaining this package and haven't been for years. The only downstream dependency is hledger, so the author(s) of hledger can sort it out if they want to keep using this library.

I'm happy to hand over the library to anyone who wants to maintain it.

**Comment by simonmichael** [comment]
Ok, I'll take it over unless/until someone else shows up. @liamoc, could you grant me (SimonMichael) maintainer access on Hackage at http://hackage.haskell.org/package/wizards/maintainers/edit ?

**Comment by liamoc** [comment]
Done.

**Comment by simonmichael** [comment]
Thanks @liamoc. I've been able to fix the immediate issue with a hackage revision. Followup actions:

- I've left you as a hackage maintainer - feel free to remove yourself if you prefer
- At some point I'll upload a small release to update the hackage metadata, changing the maintainer and repo addresses.
- Would you like to transfer ownership of the wizards repo to me ? It seems cleaner than having hackage point to "fork of...". Or, I can make a fork. Or, and I'll probably try to do this at some point, transfer it to the haskell organisation on github.
