### ISSUE TITLE
Needs update for mtl-2.2

### ISSUE THREAD

**Issue by nomeata** [liamoc/wizards#5]
Please update the package to work with mtl-2.2

**Comment by peti** [comment]
Please upload the new version to Hackage! We have trouble building `hledger` in NixOS because the wizards package won't compile with mtl 2.2.x, and it would be great to have that fixed.

**Comment by simonmichael** [comment]
Ping.. can you do a release, or shall we do it ?

**Comment by liamoc** [comment]
Sorry, I have been in hospital for the past few weeks, and then paper deadline for SOSP was yesterday.

All updated now. Check Hackage.

Liam

**Comment by simonmichael** [comment]
Thank you very much! Best wishes.

**Comment by simonmichael** [comment]
Looks like this could be closed ?
